import {
  ClerkProvider,
} from "@clerk/nextjs";
import "./globals.css";
import { Poppins, Urbanist } from "next/font/google";
import { Provider } from "@/tanstack/provider";

const font = Urbanist({ weight: ["400", "500"], subsets: ["latin"] });

export const metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.className}`}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
