import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";

export const metadata = {
  title: "Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={``}>
        {/* <header>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header> */}
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
